### ISSUE TITLE
Monitor only shows game for last joined players

### ISSUE THREAD

**Issue by aeosys** [MattiLehtinen/ai-nibbles-monitor#1]
Joining third player to server stops monitoring current game and fourth player starts a second game which is shown. You should be able to select game to watch or stay with current game if it is running.

**Comment by MattiLehtinen** [comment]
It is currently possible only to view the latest game because server does not have other API commands implemented for viewers. Please post the feature request to ai-nibbles-server. Closing because it's not monitor bug.
