### ISSUE TITLE
Bug on level / map rendering

### ISSUE THREAD

**Issue by tarlepp** [MattiLehtinen/ai-nibbles-monitor#6]
On start monitor don't show whole level, screenshot to demonstrate this:

![image](https://cloud.githubusercontent.com/assets/595561/6887069/0eaf953e-d65c-11e4-8d2b-278e7b518099.png)

**Comment by MattiLehtinen** [comment]
Do you have latest revision of the viewer?

**Comment by tarlepp** [comment]
Aaah, that did the trick, I was using old version of monitor.
